spring.application.name=tutorial

spring.config.import=optional:file:./.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

employees.api.base.url=http://localhost:8081

deploy.environment=dev


logging.level.org.springframework.web=DEBUG

#security configuration
spring.security.user.name=kishan
spring.security.user.password=password


jwt.secretKey=${JWT_SECRET_KEY}

# MCP server configuration
spring.ai.mcp.server.name=tutorial-mcp
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.type=SYNC